default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: P1UmodzAm
  host: mysql_service

development:
  <<: *default
  database: database-name-development

test:
  <<: *default
  database: database-name-test
